### PR TITLE
Allow searches for @user@host

### PR DESCRIPTION
**Pull request by winks**
This is a minor nitpick, but the Mastodon search field accepts @user@host (and I think it also promotes this by displaying it this way on people's profile).

I am not sure if it's really a Mastodon-only thing, but it seems to be widespread enough that I've had to do it for 50% of the people who posted their fedi handles on Twitter.

### CODE REVIEW

**Comment by vrthra** [comment]
I think this possibly fixes part of https://github.com/toddsundsted/ktistec/issues/34 (trimming the whitespace will fix the rest).

**Comment by winks** [comment]
Added a second commit for the whitespaces because I hadn't seen #34. This should fix both mentioned issues.

**Comment by toddsundsted** [comment]
@winks thanks! this looks good.

tests would be helpful. the tests are in spec/controllers/searches_spec.cr. at a minimum, i'd recommend tests in "given a handle" that check for stripping the leading "@" and tests in "given a URL to an actor" and "given a URL to an object" that check that whitespace is removed

**Comment by toddsundsted** [comment]
screwed up the merge while testing this—at least from github's perspective.

the two commits are in main now, so i'm closing this PR.

**Pull request closed without merging**
